version: '3.1'

services:
  promotion:
    image: jorgesanzb/e-commerce-promotion
    container_name: promotion-service
    ports:
      - "8082:8082"

  order:
    image: jorgesanzb/e-commerce-order
    container_name: order-service
    ports:
      - "8080:8080"

networks:
  e-commerce-network:
    external: true

