apiVersion: v1
kind: ReplicationController
metadata:
  name: order
spec:
  replicas: 3
  selector:
    app: order
  template:
    metadata:
      name: order
      labels:
        app: order
    spec:
      containers:
        - name: promotion
          image: jorgesanzb/e-commerce-order
          ports:
            - containerPort: 8080